version: 2.1

# Define reusable parameters for Docker Hub image and cache keys
defaults: &defaults
  docker:
    - image: cimg/openjdk:21.0
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Restore cached Gradle dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      # Install dependencies and cache them
      - run: gradle --version
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build and test the project
      - run: gradle build
      - run: gradle test

      # Optionally, you can set up remote Docker here if required

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/gremio_backend:latest .

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/gremio_backend:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
