scrape_configs:
  - job_name: 'Gremio Backend Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'Gremio Backend Application'