global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'gremio_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.19:9000'] # you can use the host ip address or the container name
        labels:
          application: 'Gremio Backend Application'